### ISSUE TITLE
Legworks

### ISSUE THREAD

**Issue by kennytm** [tikv/importer#2]
- [x] Setup Jenkins CI, with proper caching (currently it takes 30 minutes to compile and test the entire importer in debug mode on Travis CI)
- [x] Upload importer into the internal staging server, such that the Lightning / TiKV / TiDB-Toolkit releases can find this release tarball.
- [ ] Add README.md
- [x] Add Makefile (support cargo features, rustfmt, clippy) (#1)
- [ ] Add code coverage
- [x] Add GitHub issue / PR templates (#1)
- [x] Review GOVERNANCE.md (#1)

**Comment by kennytm** [comment]
Code coverage via `cargo tarpaulin` is blocked by tikv/tikv#4491.
